name: CD

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt
      - run: pip install pyinstaller

      - run: pyinstaller --onefile main.pyw --add-data "ico.png;."

      - uses: actions/upload-artifact@v4
        with:
          name: noteFlow-exe
          path: dist/main.exe